#!/usr/bin/env python

import argparse, du, numpy as np, json, jpt, os



def work(sampleFile, outPath):
  D = jpt.io.load(sampleFile)
  w = D['w']
  jpt.io.point_tracks_to_mot15_point2d(outPath, w)

def main(args):
  sampleFiles = du.GetFilePaths(args.sampleDir, 'gz')
  if args.tE < 0: sampleFiles = sampleFiles[args.t0:]
  else: sampleFiles = sampleFiles[args.t0:args.tE]

  try: os.makedirs(args.outDir)
  except: pass
  print(args.outDir)

  fp = du.fileparts
  args = [ (sf, f'{args.outDir}/{fp(sf)[1]}') for sf in sampleFiles ]
  du.ParforT(work, args)
  # du.For(work, args)

if __name__ == "__main__":
  parser = argparse.ArgumentParser(description='')
  parser.add_argument('sampleDir', type=str,
    help='Directory with jpt samples (.gz)')
  parser.add_argument('outDir', type=str,
    help='Path and basename of output json files')
  parser.add_argument('--t0', type=int, default=0, help='first sample index')
  parser.add_argument('--tE', type=int, default=-1, help='last sample index')
  parser.set_defaults(func=main)

  args = parser.parse_args()
  args.func(args)
